[package]
name = "codewars_with_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
itertools = "0.12.1"
lazy_static = "1.4"
regex = "1.10.4"
once_cell = "1.19.0"